---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: local-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: devuser
            - name: DB_PASSWORD
              value: devpass
            - name: DB_NAME
              value: devdb
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: local-db
spec:
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
