---
apiVersion: v1
kind: Namespace
metadata:
  name: local-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: local-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: local-db
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: local-db
spec:
  selector:
    app: postgres
  ports:
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: local-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: devuser
            - name: POSTGRES_PASSWORD
              value: devpass
            - name: POSTGRES_DB
              value: devdb
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

        - name: exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_URI
              value: "localhost:5432/devdb?sslmode=disable"
            - name: DATA_SOURCE_USER
              value: devuser
            - name: DATA_SOURCE_PASS
              value: devpass
          # resources:
          #   limits:
          #     memory: "64"
          #     cpu: "100m"
          #   requests:
          #     memory: "32"
          #     cpu: "50m"

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
